### ISSUE TITLE
Feature request: Please add a smoke detector

### ISSUE THREAD

**Issue by sergewddm** [mafof/node-red-contrib-xiaomi-smart-home#5]
Please add a Xiaomi Mijia Honeywell Fire Alarm Detector or the ability to receive all messages from the gateway. I did not receive any messages from the smoke detector, using xiaomi-smart-home.
If I listen directly to the UDP port 9898, I receive messages from the smoke detector:
`{"cmd":"report", "model":"smoke","sid":"158d00015b78ed","short_id":48082,"data":"{"alarm":"0"}"}`

по русски:
Пожалуйста, добавьте возможность получения всех сообщений от шлюза Xiaomi (например в виде галочки в настройках). Т.к. сейчас поддерживаются далеко не все. В частности, я не смог получать сообщения от датчика пожара (дыма) Xiaomi Mijia Honeywell. 

Спасибо за ваш труд. Узел node-red-contrib-xiaomi-smart-home очень удобный в применении.

**Comment by mafof** [comment]
Поставьте версию 0.1.1, там есть поддержка всех устройств.
